GRANT DELETE, INSERT, SELECT, UPDATE ON PR.PR_ANTEC_CRED_GTT TO BI;

GRANT DELETE, INSERT, SELECT, UPDATE ON PR.PR_ANTEC_CRED_GTT TO BPR;

GRANT DELETE, INSERT, SELECT, UPDATE ON PR.PR_ANTEC_CRED_GTT TO BPL;

GRANT DELETE, INSERT, SELECT, UPDATE ON PR.PR_ANTEC_CRED_GTT TO PL;

GRANT DELETE, INSERT, SELECT, UPDATE ON PR.PR_ANTEC_CRED_GTT TO BTC;

GRANT DELETE, INSERT, SELECT, UPDATE ON PR.PR_ANTEC_CRED_GTT TO TC;

GRANT DELETE, INSERT, SELECT, UPDATE ON PR.PR_ANTEC_CRED_GTT TO BGT;

GRANT DELETE, INSERT, SELECT, UPDATE ON PR.PR_ANTEC_CRED_GTT TO GT;

GRANT DELETE, INSERT, SELECT, UPDATE ON PR.PR_ANTEC_CRED_GTT TO BCE;

GRANT DELETE, INSERT, SELECT, UPDATE ON PR.PR_ANTEC_CRED_GTT TO CE;

GRANT DELETE, INSERT, SELECT, UPDATE ON PR.PR_ANTEC_CRED_GTT TO BCC;

GRANT DELETE, INSERT, SELECT, UPDATE ON PR.PR_ANTEC_CRED_GTT TO CC;

GRANT SELECT ON PR.PR_ANTEC_CRED_GTT TO TMP_ANALISTAS;

GRANT SELECT ON PR.PR_ANTEC_CRED_GTT TO TMP_CONSULTA;

GRANT SELECT ON PR.PR_ANTEC_CRED_GTT TO ROL_CONSULTA;

GRANT EXECUTE ON pr.empresa_en_antec_cred TO BI;

GRANT EXECUTE ON pr.empresa_en_antec_cred TO BPR;

GRANT EXECUTE ON pr.empresa_en_antec_cred TO BPL;

GRANT EXECUTE ON pr.empresa_en_antec_cred TO PL;

GRANT EXECUTE ON pr.empresa_en_antec_cred TO BTC;

GRANT EXECUTE ON pr.empresa_en_antec_cred TO TC;

GRANT EXECUTE ON pr.empresa_en_antec_cred TO BGT;

GRANT EXECUTE ON pr.empresa_en_antec_cred TO GT;

GRANT EXECUTE ON pr.empresa_en_antec_cred TO BCE;

GRANT EXECUTE ON pr.empresa_en_antec_cred TO CE;

GRANT EXECUTE ON pr.empresa_en_antec_cred TO BCC;

GRANT EXECUTE ON pr.empresa_en_antec_cred TO CC;

