GRANT DELETE, INSERT, SELECT, UPDATE ON PR.PR_ANTEC_CRED_GTT TO BI;

GRANT DELETE, INSERT, SELECT, UPDATE ON PR.PR_ANTEC_CRED_GTT TO BPR;

GRANT DELETE, INSERT, SELECT, UPDATE ON PR.PR_ANTEC_CRED_GTT TO BPL;

GRANT DELETE, INSERT, SELECT, UPDATE ON PR.PR_ANTEC_CRED_GTT TO PL;

GRANT DELETE, INSERT, SELECT, UPDATE ON PR.PR_ANTEC_CRED_GTT TO BTC;

GRANT DELETE, INSERT, SELECT, UPDATE ON PR.PR_ANTEC_CRED_GTT TO TC;

GRANT DELETE, INSERT, SELECT, UPDATE ON PR.PR_ANTEC_CRED_GTT TO BGT;

GRANT DELETE, INSERT, SELECT, UPDATE ON PR.PR_ANTEC_CRED_GTT TO GT;

GRANT DELETE, INSERT, SELECT, UPDATE ON PR.PR_ANTEC_CRED_GTT TO BCE;

GRANT DELETE, INSERT, SELECT, UPDATE ON PR.PR_ANTEC_CRED_GTT TO CE;

GRANT DELETE, INSERT, SELECT, UPDATE ON PR.PR_ANTEC_CRED_GTT TO BCC;

GRANT DELETE, INSERT, SELECT, UPDATE ON PR.PR_ANTEC_CRED_GTT TO CC;

GRANT SELECT ON PR.PR_ANTEC_CRED_GTT TO TMP_ANALISTAS;

GRANT SELECT ON PR.PR_ANTEC_CRED_GTT TO TMP_CONSULTA;

GRANT SELECT ON PR.PR_ANTEC_CRED_GTT TO ROL_CONSULTA;



--DROP PUBLIC SYNONYM PR_ANTEC_CRED_GTT;

CREATE OR REPLACE PUBLIC SYNONYM PR_ANTEC_CRED_GTT FOR PR.PR_ANTEC_CRED_GTT;
