
--DROP PUBLIC SYNONYM PR_ANTEC_CRED_GTT;

CREATE OR REPLACE PUBLIC SYNONYM PR_ANTEC_CRED_GTT FOR PR.PR_ANTEC_CRED_GTT;

--DROP PUBLIC SYNONYM empresa_en_antec_cred;

CREATE OR REPLACE PUBLIC SYNONYM empresa_en_antec_cred FOR pr.empresa_en_antec_cred;