UPDATE PA.FORMAS
SET DESCRIPCION = 'Antecedentes Crediticios', --'Antecedentes en el B.U.S.A.',
VERSION_VALIDA = '1.6.3', --'1.6.2',
FECHA = SYSDATE, --TO_DATE('24/12/2024 23:06:32', 'DD/MM/YYYY HH24:MI:SS'),
COD_USUARIO = 'mocastro', --'CARQUISPE',
CAMBIO_REALIZADO = 'FSN1852 Unificacion de operaciones de creditos e1 e5 e10 e11' --'carquispe 12/12/2024 CAMBIO DE FUNCION Y VALIDACION DE CAMPO'
WHERE COD_SISTEMA = 'PR' AND NOM_FORMA = 'PR0050';
-- 1 row updated
UPDATE PA.FORMAS
SET DESCRIPCION = 'Antecedentes en el B.U.S.A.',
VERSION_VALIDA = '1.6.2',
FECHA = TO_DATE('24/12/2024 23:06:32', 'DD/MM/YYYY HH24:MI:SS'),
COD_USUARIO = 'CARQUISPE',
CAMBIO_REALIZADO = 'carquispe 12/12/2024 CAMBIO DE FUNCION Y VALIDACION DE CAMPO'
WHERE COD_SISTEMA = 'PR' AND NOM_FORMA = 'PR0050';
-- 1 row updated